version: 2
jobs:
  ruby-2.6.3:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: rails_blog
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

  ruby-2.5.5:
    docker:
      - image: circleci/ruby:2.5.5-stretch-node
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: rails_blog
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

  ruby-2.4.6:
    docker:
      - image: circleci/ruby:2.4.6-stretch-node
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: rails_blog
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

workflows:
  version: 2
  build:
    jobs:
      - "ruby-2.6.3"
      - "ruby-2.5.5"
      - "ruby-2.4.6"




